# Site settings
title: WP Clarkson
email: support@level-level.com
description: WP Clarkson is a WordPress Twig plugin and starter theme.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wp-clarkson.com" # the base hostname & protocol for your site

author:
  twitter: levellevel
twitter:
  username: levellevel
  card: summary

github:
  username: level-level

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - readme.md
  - bin
  - Gemfile
  - Gemfile.lock

permalink: /blog/:title.html
paginate: 10
paginate_path: /blog/page:num

collections:
  theme:
    output: true
    permalink: /theme/docs/:path/
  core:
    output: true
    permalink: /core/docs/:path/

global:
  github:
    core: "https://github.com/level-level/Clarkson-Core"
    theme: "https://github.com/level-level/Clarkson-Theme"
  pagetitle:
    core: "Clarkson Core"
    theme: "Clarkson Theme"
