# Site settings
title: WP Clarkson - The missing theming layer for WordPress
email: support@level-level.com
description: WP Clarkson is a WordPress Twig plugin and starter theme that acts as the missing theming layer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wp-clarkson.com" # the base hostname & protocol for your site

author:
  twitter: levellevel
  website: https://level-level.com
  github: level-level
twitter:
  username: levellevel
  card: summary

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - readme.md
  - bin
  - Gemfile
  - Gemfile.lock

permalink: /blog/:title.html
paginate: 10
paginate_path: /blog/page:num

collections:
  theme:
    output: true
    permalink: /theme/docs/:path/
  core:
    output: true
    permalink: /core/docs/:path/