# Site settings
title: Clarkson
email: support@level-level.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://level-level.github.io" # the base hostname & protocol for your site
twitter_username: levellevel
github_username:  level-level

# Build settings
markdown: kramdown

collections:
  theme:
    output: true
    permalink: /theme/docs/:path/
  core:
    output: true
    permalink: /core/docs/:path/

global:
  github:
    core: "https://github.com/level-level/Clarkson-Core"
    theme: "https://github.com/level-level/Clarkson-Theme"
  pagetitle:
    core: "Clarkson Core"
    theme: "Clarkson Theme"
